# Generated by Django 3.2.6 on 2022-07-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
    ]
