# Generated by Django 3.2.6 on 2022-08-31 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80, verbose_name='Product Name')),
                ('model_name', models.CharField(max_length=80, verbose_name='Model Name')),
                ('serial_no', models.CharField(max_length=80, verbose_name='Serial No.')),
                ('mobile', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 12, 49, 44, 687017))),
                ('completed_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 12, 49, 44, 687017))),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Repaired'), (3, 'Closed')], default=1)),
            ],
        ),
    ]
