# Generated by Django 3.2.6 on 2022-08-31 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220831_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 13, 8, 5, 981069)),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 13, 8, 5, 981069)),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
